language: java
sudo: false
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xms4g -Xmx4g"
    - JAVA_OPTS="-Xms4g -Xmx4g"

script: mvn clean verify -Pqulice
