language: java
jdk:
  - oraclejdk8
sudo: false
os:
  - linux
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xms4g -Xmx4g"
    - JAVA_OPTS="-Xms4g -Xmx4g"

before_install:
 - |
   if [ "$TRAVIS_OS_NAME" = "osx" ]
   then
     export JAVA_HOME="$(/usr/libexec/java_home)"
   fi

script: mvn clean install -Pqulice -Pcoveralls
